name: my_cving
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  go_router: ^5.0.5
  responsive_framework: ^0.2.0
  flutter_riverpod: ^2.0.2
  rive: ^0.9.1
  provider: ^6.0.3
  intl: ^0.17.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.2.1
  animated_text_kit: ^4.2.2
  flutter_clean_architecture: ^5.0.3
  url_launcher: ^6.1.6
  logger: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  collection: ^1.16.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^4.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/logo/
    - assets/jpg/
    - assets/files/
    - google_fonts/
